services:
  worker:
    build: .
    command: ["celery", "-A", "equipment_cpe.celery_app:celery_app", "worker", "-l", "info", ]
    env_file:
      - .env
    depends_on:
      - rabbit

  backend:
    build: .
    command:
      [
        "uvicorn",
        "--factory",
        "equipment_cpe.app:create_app",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
      ]
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - worker

  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_LOGIN}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
